name: Deploy

on:
  workflow_run:
    workflows: ["Python application test"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List contents of /home/runner/work
      run: ls -la /home/runner/work

    - name: Print workspace directory
      run: ls -R ${{ github.workspace }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install doctl
      run: |
        curl -L https://github.com/digitalocean/doctl/releases/download/v1.64.0/doctl-1.64.0-linux-amd64.tar.gz | tar xvz
        sudo mv doctl /usr/local/bin

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Add SSH key to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 146.190.226.82 >> ~/.ssh/known_hosts

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 146.190.226.82 >> ~/.ssh/known_hosts    
    
    - name: Deploy to server
      run: |
        echo "GitHub Workspace: CD/main.py"
        echo "rsync --quiet CD/main.py /documents/CD_Assesment/main.py"
        doctl compute ssh ubuntu-s-1vcpu-512mb-10gb-ams3-01 --ssh-command "mkdir -p /documents/CD_Assesment && rsync --quiet CD/main.py CD/requirements.txt /documents/CD_Assesment/ && cd /documents/CD_Assesment && python3 -m venv venv && source venv/bin/activate && pip install -r requirements.txt && sudo systemctl restart cd_assesment" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null    
    
    env:  
      DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}