name: Test and Deploy

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        export FLASK_APP=main.py
        pytest

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install doctl
      run: |
        curl -L https://github.com/digitalocean/doctl/releases/download/v1.64.0/doctl-1.64.0-linux-amd64.tar.gz | tar xvz
        sudo mv doctl /usr/local/bin
    
    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}
          
    - name: Add SSH key to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -t rsa -H 146.190.226.82 >> ~/.ssh/known_hosts
        
    - name: Deploy to server
      run: |
        doctl compute ssh ubuntu-s-1vcpu-512mb-10gb-ams3-01 --ssh-command "mkdir -p /documents/CD_Assesment && rsync -e 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' --quiet ./main.py ./requirements.txt ubuntu@146.190.226.82:/documents/CD_Assesment/ && cd /documents/CD_Assesment && python3 -m venv venv && source venv/bin/activate && pip install -r requirements.txt && sudo systemctl restart cd_assesment"            
      
      env:  
        DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}