name: Python application test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip uninstall -y jinja2
        pip install jinja2==2.11.3
        pip uninstall -y markupsafe
        pip install markupsafe==1.1.1
        pip install -r requirements.txt
    - name: Run tests
      run: |
        export FLASK_APP=main.py
        pytest